# Generated by Django 3.2.6 on 2021-08-12 03:18

from django.db import migrations, models
import providers.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=17, validators=[providers.validators.phone_regex])),
                ('language', models.CharField(max_length=20)),
                ('currency', models.CharField(max_length=5)),
            ],
        ),
    ]
